[build]
# The index HTML file to drive the bundling process
target = "index.html"
# Build output directory
dist = "dist"

[watch]
# Watch for changes in the src directory
watch = ["src"]

[serve]
# The address to serve on
address = "127.0.0.1"
# The port to serve on
port = 8080
# Open browser automatically
open = true
