name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64, aarch64]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    # Install dependencies only for Linux
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config gcc-aarch64-linux-gnu
        
    # Set up Rust toolchain
    - name: Set up Rust toolchain
      run: |
        rustup toolchain install stable
        rustup target add ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}
    
    # Build the project with vendored OpenSSL on aarch64
    - name: Build
      run: |
        if [ "${{ matrix.target }}" == "aarch64" ] && [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          cargo build --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'linux-latest' && 'linux-gnu' }} --features "vendored"
        else
          cargo build --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}
        fi
    
    # Run tests
    - name: Run tests
      run: |
        if [ "${{ matrix.target }}" == "aarch64" ] && [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          cargo test --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'linux-latest' && 'linux-gnu' }} --features "vendored"
        else
          cargo test --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}
        fi
    
    # Package the artifacts
    - name: Package artifact
      run: |
        mkdir -p artifacts
        cp target/${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}/debug/libgldf_rs.* artifacts/
    
    # Upload the artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gldf_rs-${{ matrix.os }}-${{ matrix.target }}
        path: artifacts/
