name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64, aarch64]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    # Install dependencies only for Linux
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev gcc-aarch64-linux-gnu
    
    # Set up Rust toolchain
    - name: Set up Rust toolchain
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          if [ "${{ matrix.target }}" == "x86_64" ]; then
            rustup set default-host x86_64-apple-darwin
          else
            rustup set default-host aarch64-apple-darwin
          fi
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          rustup set default-host x86_64-pc-windows-msvc
        fi
        rustup toolchain install stable
        rustup target add ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}
    
    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}

    - name: Run tests
      run: cargo test --verbose --target ${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}

    - name: Package artifact
      run: |
        mkdir -p artifacts
        cp target/${{ matrix.target }}-unknown-${{ matrix.os == 'windows-latest' && 'pc-windows-msvc' || matrix.os == 'macos-latest' && 'apple-darwin' || 'linux-gnu' }}/debug/libgldf_rs.* artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gldf_rs-${{ matrix.os }}-${{ matrix.target }}
        path: artifacts/
