name: Rust-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            architecture: x86_64
            docker_image: rust:latest
          - os: ubuntu-latest
            architecture: aarch64
            docker_image: rust:latest
          - os: windows-latest
            architecture: x86_64
            docker_image: mcr.microsoft.com/windows/servercore:ltsc2022
          - os: macos-latest
            architecture: x86_64
          - os: macos-latest
            architecture: aarch64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'aarch64'
      run: |
        docker run --rm --privileged tonistiigi/binfmt:latest --install aarch64

    - name: Build with Docker
      if: matrix.os == 'ubuntu-latest'
      run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp ${{ matrix.docker_image }} cargo build --verbose

    - name: Build on Windows or macOS
      if: matrix.os != 'ubuntu-latest'
      run: cargo build --verbose

    - name: Run tests with Docker
      if: matrix.os == 'ubuntu-latest'
      run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp ${{ matrix.docker_image }} cargo test --verbose

    - name: Run tests on Windows or macOS
      if: matrix.os != 'ubuntu-latest'
      run: cargo test --verbose

    - name: Upload build artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.architecture }}-build
        path: |
          target/debug
          target/release
